<?php
 $base_config = array (
  'admin_host_self' => $host . 'exam/admin/',
  'exam_root' => $host . 'exam/',
  'exam_open' => '1',
  'why_close' => '',
  'server_independ' => '0',
  'kaojuan_livetime' => '48',//小时	考卷有效期
  'kaojuan_timeout' => '4',//小时	考卷答题超时时间
  'func_cachetime' => '360',
  'exam_title' => 'PPExam',
  'kaojuan_autotime' => '100',
  'kaojuan_delaytime' => '10',
  'exam_paymoney' => '0',
  'exam_usemoney' => '1',
  'easy_cachetime' => '360',
  'exam_onlyone_kaojuan' => '0',
  'easy_use_index' => '0',
  'ban_kjname' => '0',
  'kui_start' => '1',
  'exam_use_editor' => '1',
  'exam_editor_width' => '100%',
  'exam_editor_hight' => '400',
  'exam_editor_toolbar' => '0',
  'editor_userfiles' => 'userfiles',
  'exam_pagebreak_num' => '15',
  'exam_batupdate_start' => '1',
  'exam_batupdate_end' => '3',
  'exam_reportmoney_num' => '1',
  'exam_reportmoney' => '0',
  'exam_max_num' => '200',
  'exam_class_use' => '1',
  'exam_pushmoney_num' => '0',
  'exam_pushmoney' => '0',
  'exam_allowpush' => '0',
  'exam_tishi_position' => '1',
  'exam_word_down' => '0',
  'pageset' => 
  array (
    'search' => '15',
    'my_kaojuan' => '15',
    'paihang' => '15',
  ),
  'pageset_admin' => 
  array (
    'tiku' => '10',
    'shiti' => '10',
    'shijuan' => '10',
    'class' => '10',
    'kaojuan' => '10',
    'errorreport' => '10',
    'xuanti' => '10',
    'xuanti_view' => '10',
  ),
  'exam_select_wait' => '1',
  'exam_select_waittime' => '10',
  'ip_ban' => '0',
  'ip_ban_exam' => '0',
  'exam_cktimes_use' => '1',
  'kaojuan_before_select' => '1440',
  'exam_use_ueditor' => '1',
  'global_onlyone_kaojuan' => '0',
  'exam_ucfeed_start' => '1',
  'exam_ucfeed_close' => '1',
)
?>