INSERT INTO `#@__flink` VALUES (1, 1, 'https://github.com/guozesheng/ccu', '实验仪器管理系统', '长春大学实验仪器管理系统', '', '#', '2012-05-19 11:31:29', 1, 2);

INSERT INTO `#@__menu` (`id`, `name`, `url`, `reid`, `rank`) VALUES
(9, '系统变量设置', 'system_basic.php', 1, ''),
(11, '仪器入库', 'equip_add.php', 1, ''),
(12, '仪器列表', 'equip_add.php?action=seek', 1, ''),
(13, '仪器借用管理', 'borrow_ask.php', 1, ''),
(14, '用户管理', 'system_guest.php', 1, ''),
(16, '系统变量设置', 'system_basic.php', 2, ''),
(17, '产品基本信息', 'system_basic_cp.php', 2, ''),
(18, '产品分类管理', 'system_class.php', 2, ''),
(19, '计量单位管理', 'system_dw.php', 2, ''),
(20, '供应商管理', 'system_gys.php', 2, ''),
(21, '员工管理', 'system_worker.php', 2, ''),
(22, '仓库管理', 'system_lab.php', 2, ''),
(50, '仪器查询', 'equip_add.php?action=seek', 9, ''),
(81, '报修历史', 'equip_repairlist.php', 12, ''),
(80, '报修申请', 'equip_repairlist.php?action=seek', 12, ''),
(36, '添加新用户', 'system_guest.php?action=new', 6, ''),
(37, '用户列表', 'system_guest.php', 6, ''),
(38, '用户分组', 'guest_group.php', 6, ''),
(39, '申请待批', 'borrow_ask.php', 7, ''),
(40, '未还列表', 'borrow_list.php?ac=noreturn', 7, ''),
(41, '借用历史', 'borrow_list.php', 7, ''),
(83, '申请列表', 'equip_repair.php?action=do', 14, ''),
(82, '维修待批', 'equip_repair.php', 14, ''),
(49, '仪器入库', 'equip_add.php', 9, ''),
(45, '报废待批', 'equip_dropask.php', 8, ''),
(46, '报废列表', 'equip_droplist.php', 8, ''),
(47, '申请历史', 'equip_dropask.php?action=seek', 8, ''),
(84, '维修历史', 'equip_repair.php?action=seek', 14, ''),
(55, '仪器分类', 'system_class.php', 9, ''),
(56, '仪器查询', 'equip.php?action=seek', 10, ''),
(57, '已借仪器', 'equip_bolist.php?ac=noreturn', 10, ''),
(58, '借用历史', 'equip_bolist.php', 10, ''),
(59, '借用申请', 'equip_asklist.php', 10, ''),
(78, '申请列表', 'equip_droplist.php?action=seek', 11, ''),
(79, '申请历史', 'equip_droplist.php', 11, '');

INSERT INTO `#@__topmenu` (`id`, `name`, `url`, `flag`, `permission`) VALUES
(1, '快捷操作菜单', '', 0, 1),
(2, '系统设置', 'system_basic.php', 1, 1),
(14, '仪器维修', 'equip_repair.php?action=do', 1, 1),
(6, '用户管理', 'system_guest.php', 1, 1),
(7, '借用管理', 'borrow_ask.php', 1, 1),
(8, '仪器报废', 'equip_dropask.php', 1, 1),
(9, '仪器管理', 'equip_add.php?action=seek', 1, 1),
(12, '仪器报修', 'equip_repairlist.php', 1, 2),
(10, '仪器管理', 'equip.php?action=seek', 1, 2),
(11, '仪器报废', 'equip_droplist.php', 1, 2);